### ISSUE TITLE
The index of the selected element was out of range

### ISSUE THREAD

**Issue by eric-simu** [simular-ai/OpenACI#12]
I experienced the following issue when running the command "show all unread emails in gmail", which seems to be a bug in the grounding module. 

```
['import pyautogui; pyautogui.click(34.0, 53.0, clicks=1, button="left")']
id	role	title	text
The index of the selected element was out of range.
The index of the selected element was out of range.
Traceback (most recent call last):
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 178, in find_element
    selected_element = self.nodes[int(element_id)]
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 291, in type_and_enter
    node = self.find_element(element_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 181, in find_element
    selected_element = self.nodes[0]
                       ~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 178, in find_element
    selected_element = self.nodes[int(element_id)]
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericwang/research/openaci-new/openaci/cli_app.py", line 129, in <module>
    main()
  File "/Users/ericwang/research/openaci-new/openaci/cli_app.py", line 124, in main
    run(query)
  File "/Users/ericwang/research/openaci-new/openaci/cli_app.py", line 104, in run
    info, code = agent.predict(instruction=instruction, obs=obs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/agent/UIAgent.py", line 174, in predict
    exec_code = eval(plan_code)
                ^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 293, in type_and_enter
    node = self.find_element(0)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 181, in find_element
    selected_element = self.nodes[0]
                       ~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by simularlyon** [comment]
`element_id` is produced by LLM so it's quite possible to hallucinate

**Comment by eric-simu** [comment]
Since we have all the element IDs, we can have a sanity check to ensure the ID must come from the ID list before clicking. Wrong clicking is a reasoning/grounding problem of LLMs, but out of index is simply a bug of the ACI framework.

**Comment by eric-simu** [comment]
This seems to be caused by #19
