### ISSUE TITLE
grounding Assertion Error

### ISSUE THREAD

**Issue by eric-simu** [simular-ai/OpenACI#20]
The task is `open the most recent email in gmail`. The agent did everything perfectly and actually opened it. But there appeared the following assertion error. This is based on the new code after PR #18.

```
'plan_code': 'agent.click(204)', 'reflection': 'The trajectory indicates an adjustment was made due to the previous action not achieving the intended result. The updated plan to select the appropriate profile before navigating to Gmail is a reasonable correction. Continue with the next steps as planned.'}
['import pyautogui; pyautogui.click(981.0, 258.0, clicks=1, button="left")']
Traceback (most recent call last):
  File "/Users/ericwang/research/openaci-new/openaci/cli_app.py", line 132, in <module>
    main()
  File "/Users/ericwang/research/openaci-new/openaci/cli_app.py", line 127, in main
    run(query)
  File "/Users/ericwang/research/openaci-new/openaci/cli_app.py", line 104, in run
    info, code = agent.predict(instruction=instruction, obs=obs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/agent/UIAgent.py", line 133, in predict
    agent = GroundingAgent(
            ^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 65, in __init__
    self.nodes, self.linearized_accessibility_tree = self.linearize_and_annotate_tree(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 150, in linearize_and_annotate_tree
    preserved_nodes = self.preserve_nodes(tree).copy()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ericwang/research/openaci-new/openaci/macos/Grounding.py", line 143, in preserve_nodes
    assert node.attribute('AXPosition') is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by saa1605** [comment]
This is the issue with the tree nodes getting updated during run.

**Comment by eric-simu** [comment]
Is this why we have the wait() function? How do we address this?
